DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY AUTO_INCREMENT, TITLE VARCHAR(255));
CREATE TABLE BOOKS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(255),
  AUTHOR_ID BIGINT NOT NULL,
  GENRE_ID BIGINT NOT NULL,
  FOREIGN KEY (AUTHOR_ID) references AUTHORS(ID),
  FOREIGN KEY (GENRE_ID) references GENRES(ID)
);