DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE BOOKS(ID INT PRIMARY KEY AUTO_INCREMENT, TITLE VARCHAR(255), AUTHOR_ID INT, GENRE_ID INT);
CREATE TABLE AUTHORS(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));
CREATE TABLE GENRES(ID INT PRIMARY KEY AUTO_INCREMENT, TITLE VARCHAR(255));